spring:
  cloud:
    azure:
      eventhubs:
        namespace: evhns-fzgdhkc25e3jm # ${AZURE_EVENTHUBS_NAMESPACE}
        processor:
          checkpoint-store:
            container-name: containerone # ${AZURE_STORAGE_CONTAINER_NAME}
            account-name: stfzgdhkc25e3jm # ${AZURE_STORAGE_ACCOUNT_NAME}
