spring:
  cloud:
    function:
      definition: consume1;supply1;consume2;supply2
    stream:
      bindings:
        consume1-in-0:
          destination: eventhub01 # ${AZURE_EVENTHUB_NAME_01}
          group: $Default # ${AZURE_EVENTHUB_CONSUMER_GROUP_01}
        supply1-out-0:
          destination: eventhub01 # ${AZURE_EVENTHUB_NAME_01}
        consume2-in-0:
          binder: eventhub-2
          destination: eventhub02 # ${AZURE_EVENTHUB_NAME_02}
          group: $Default # ${AZURE_EVENTHUB_CONSUMER_GROUP_02}
        supply2-out-0:
          binder: eventhub-2
          destination: eventhub02 # ${AZURE_EVENTHUB_NAME_02}
      binders:
        eventhub-1:
          type: eventhubs
          default-candidate: true
          environment:
            spring:
              cloud:
                azure:
                  eventhubs:
                    namespace: evhns-fzgdhkc25e3jm
                    processor:
                      checkpoint-store:
                        container-name: containerone
                        account-name: stfzgdhkc25e3jm
        eventhub-2:
          type: eventhubs
          default-candidate: false
          environment:
            spring:
              cloud:
                azure:
                  eventhubs:
                    namespace: evhns-sgk76kfznouag # ${EVENTHUB_NAMESPACE_01}
                    processor:
                      checkpoint-store:
                        container-name: containertwo # ${AZURE_STORAGE_CONTAINER_NAME}
                        account-name: stfzgdhkc25e3jm # ${AZURE_STORAGE_ACCOUNT_NAME}
      eventhubs:
        bindings:
          consume1-in-0:
            consumer:
              checkpoint:
                mode: MANUAL
          consume2-in-0:
            consumer:
              checkpoint:
                mode: MANUAL
      poller:
        initial-delay: 0
        fixed-delay: 1000
